- name: "Install Node.js 13"
  become: true
  shell: | 
    # install node.js lts version as our node.js version
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt install -y nodejs
            
    # use n version manager to use node.js 13.8.0
    sudo npm install -g n
    sudo n 13.8.0


- name: "Install PM2 globally"
  npm:
    name: pm2
    global: yes 